### ISSUE TITLE
Is it possible to get an arxiv formatted paper , totally by CoI-Agent

### ISSUE THREAD

**Issue by CoderYiFei** [DAMO-NLP-SG/CoI-Agent#2]

**Comment by jianghuyihei** [comment]
> _No description provided._

Right now, it’s not feasible because expecting an LLM to recreate ideas from scratch is unlikely. If this hurdle could be overcome, then writing the rest of the paper would be relatively easy for an LLM. There are efforts like Ai-Scientist trying to write papers from the ground up, but they can only handle simple ideas and are still far from real scientific research.
